import type { Metadata } from "next";
//import localFont from "next/font/local";
import "./globals.css";
import "./style.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { Anta } from "next/font/google";

import BootstrapClient from "@/components/BootstrapClient";
import OrangeButton from "@/components/OrangeButton";

const anta = Anta( {
  weight: "400",
  display: "swap",
  subsets: ["latin-ext"]
})


export const metadata: Metadata = {
  title: "HS Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <body className={`${anta.className}`}>

        <nav className="navbar navbar-expand-lg">
          <div className="container justify-content-between">
            <a className="navbar-brand" href="#"><span className="text-Orange">H</span><span className="text-Blue">S</span>market</a>
            <form className="d-flex navbarSearch" role="search">
              <input className="form-control" type="search" placeholder="Keresés" aria-label="Search"/>
            </form>
            <OrangeButton props={{
              name: "Bejelentkezés",
              href: "#"
            }} />
          </div>
        </nav>

        {children}

      </body>
    </html>
  );
}
